# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assert_info',
            fields=[
                ('assertid', models.IntegerField(primary_key=True, serialize=False)),
                ('assert_name', models.CharField(max_length=100)),
                ('assert_data', models.CharField(max_length=200)),
                ('task_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'assert_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='task_que',
            fields=[
                ('taskid', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('inqueuetime', models.DateTimeField()),
                ('starttime', models.DateTimeField()),
                ('finishtime', models.DateTimeField()),
                ('progress', models.IntegerField()),
                ('status', models.IntegerField()),
                ('taskmsg', models.CharField(max_length=100)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'task_que',
                'managed': False,
            },
        ),
    ]
